# Inclui as regras de lint recomendadas para Flutter
include: package:flutter_lints/flutter.yaml

# Você pode adicionar outras configurações personalizadas aqui se necessário
linter:
  rules:
    # Regras adicionais personalizadas podem ser configuradas aqui
    avoid_print: true  # Não permitir o uso de print (opcional, já pode estar no flutter_lints)
    always_specify_types: true  # Exigir que tipos sejam especificados
    prefer_single_quotes: true  # Preferir aspas simples ao invés de duplas

analyzer:
  errors:
    # Configurações para transformar avisos em erros
    prefer_single_quotes: info
